LIGAS_PERMITIDAS = {
    "África do Sul - Premier League",
    "Albânia - Superliga",
    "Alemanha - 2. Bundesliga",
    "Alemanha - 3. Liga",
    "Alemanha - Bundesliga",
    "Argélia - Ligue 1",
    "Argentina - Primera B Nacional",
    "Argentina - Superliga",
    "Arábia Saudita - Pro League",
    "Armênia - Premier League",
    "Austrália - A-League",
    "Áustria - Tipico Bundesliga",
    "Bélgica - First Division B",
    "Bélgica - Pro League",
    "Bolívia - Liga De Futbol Prof",
    "Brasil - Serie A",
    "Brasil - Serie B",
    "Brasil - Serie C",
    "Bulgária - Parva Liga",
    "Chile - Primera Division",
    "China - Super League",
    "Colômbia - Liga BetPlay",
    "Coréia do Sul - K-League 1",
    "Coréia do Sul - K League 2",
    "Croácia - 1. HNL",
    "Dinamarca - First Division",
    "Dinamarca - Superliga",
    "Egito - Premier League",
    "Equador - Liga Pro",
    "Escócia - Championship",
    "Escócia - League One",
    "Escócia - League Two",
    "Escócia - Premiership",
    "Eslováquia - Fortuna Liga",
    "Eslovênia - 1. SNL",
    "Espanha - La Liga",
    "Espanha - La Liga 2",
    "Estônia - Meistriliiga",
    "EUA - Major League Soccer",
    "Finlândia - Veikkausliiga",
    "França - Ligue 1",
    "França - Ligue 2",
    "Grécia - Super League",
    "Hungria - OTP Bank Liga",
    "Inglaterra - Championship",
    "Inglaterra - League One",
    "Inglaterra - League Two",
    "Inglaterra - National League",
    "Inglaterra - Premier League",
    "Irlanda - Premier Division",
    "Irlanda do Norte - Premiership",
    "Islândia - Pepsideild",
    "Israel - Ligat ha'Al",
    "Itália - Serie A",
    "Itália - Serie B",
    "Japão - J-League",
    "Japão - J2-League",
    "Lituânia - A Lyga",
    "Malásia - Super League",
    "México - Liga MX",
    "Noruega - Eliteserien",
    "Noruega - Obos-Ligaen",
    "Países Baixos - Eerste Divisie",
    "Países Baixos - Eredivisie",
    "País de Gales - Premier League",
    "Paraguai - Division 1",
    "Peru - Primera Division",
    "Polônia - Ekstraklasa",
    "Portugal - Primeira Liga",
    "Portugal - Segunda Liga",
    "Romênia - Liga 1",
    "Sérvia - Super Liga",
    "Suécia - Allsvenskan",
    "Suécia - Superettan",
    "Suíça - Super League",
    "Turquia - Super Lig",
    "Uruguai - Primera Division",
    "Venezuela - Primera Division",
}

LIMITE_JOGOS_POR_TIME = 50
