# dados consolidados
LIGAS_PERMITIDAS = {
    "África do Sul - Premier League",
    "Albânia - Superliga",
    "Alemanha - 2. Bundesliga",
    "Alemanha - 3. Liga",
    "Alemanha - Bundesliga",
    "Argélia - Ligue 1",
    "Argentina - Primera B Nacional",
    "Argentina - Superliga",
    "Arábia Saudita - Pro League",
    "Armênia - Premier League",
    "Austrália - A-League",
    "Áustria - Tipico Bundesliga",
    "Bélgica - First Division B",
    "Bélgica - Pro League",
    "Bolívia - Liga De Futbol Prof",
    "Brasil - Serie A",
    "Brasil - Serie B",
    "Brasil - Serie C",
    "Bulgária - Parva Liga",
    "Chile - Primera Division",
    "China - Super League",
    "Colômbia - Liga BetPlay",
    "Coréia do Sul - K-League 1",
    "Coréia do Sul - K League 2",
    "Croácia - 1. HNL",
    "Dinamarca - First Division",
    "Dinamarca - Superliga",
    "Egito - Premier League",
    "Equador - Liga Pro",
    "Escócia - Championship",
    "Escócia - League One",
    "Escócia - League Two",
    "Escócia - Premiership",
    "Eslováquia - Fortuna Liga",
    "Eslovênia - 1. SNL",
    "Espanha - La Liga",
    "Espanha - La Liga 2",
    "Estônia - Meistriliiga",
    "EUA - Major League Soccer",
    "Finlândia - Veikkausliiga",
    "França - Ligue 1",
    "França - Ligue 2",
    "Grécia - Super League",
    "Hungria - OTP Bank Liga",
    "Inglaterra - Championship",
    "Inglaterra - League One",
    "Inglaterra - League Two",
    "Inglaterra - National League",
    "Inglaterra - Premier League",
    "Irlanda - Premier Division",
    "Irlanda do Norte - Premiership",
    "Islândia - Pepsideild",
    "Israel - Ligat ha'Al",
    "Itália - Serie A",
    "Itália - Serie B",
    "Japão - J-League",
    "Japão - J2-League",
    "Lituânia - A Lyga",
    "Malásia - Super League",
    "México - Liga MX",
    "Noruega - Eliteserien",
    "Noruega - Obos-Ligaen",
    "Países Baixos - Eerste Divisie",
    "Países Baixos - Eredivisie",
    "País de Gales - Premier League",
    "Paraguai - Division 1",
    "Peru - Primera Division",
    "Polônia - Ekstraklasa",
    "Portugal - Primeira Liga",
    "Portugal - Segunda Liga",
    "Romênia - Liga 1",
    "Sérvia - Super Liga",
    "Suécia - Allsvenskan",
    "Suécia - Superettan",
    "Suíça - Super League",
    "Turquia - Super Lig",
    "Uruguai - Primera Division",
    "Venezuela - Primera Division",
}

LIMITE_JOGOS_POR_TIME = 50 # faz parte dos dados consolidados

LIGAS_XG = {
    "Alemanha - 2. Bundesliga",
    "Alemanha - Bundesliga",
    "Argentina - Superliga",
    "Arábia Saudita - Pro League",
    "Austrália - A-League",
    "Brasil - Serie A",
    "Bélgica - Pro League",
    "Dinamarca - Superliga",
    "EUA - Major League Soccer",
    "Escócia - Premiership",
    "Espanha - La Liga",
    "França - Ligue 1",
    "Inglaterra - Championship",
    "Inglaterra - League One",
    "Inglaterra - League Two",
    "Inglaterra - Premier League",
    "Itália - Serie A",
    "Japão - J-League",
    "Japão - J2-League",
    "México - Liga MX",
    "Noruega - Eliteserien",
    "Países Baixos - Eerste Divisie",
    "Países Baixos - Eredivisie",
    "Portugal - Primeira Liga",
    "Suécia - Allsvenskan",
    "Suíça - Super League",
    "Turquia - Super Lig",
    "Áustria - Tipico Bundesliga",
}

# URLs Manuais (Garante 100% de acerto para as ligas listadas aqui)
URLS_MANUAIS = {
    # --- TOP LIGAS (xG + ODDS 100%) ---
    "Áustria - Tipico Bundesliga": "https://redscores.com/pt-br/league/austria/tipico-bundesliga/181",
    #"Alemanha - 2. Bundesliga": "https://redscores.com/pt-br/league/germany/2-bundesliga/85",
    #"Alemanha - Bundesliga": "https://redscores.com/pt-br/league/germany/bundesliga/82",
    #"Argentina - Superliga": "https://redscores.com/pt-br/league/argentina/superliga/636",
    #"Arábia Saudita - Pro League": "https://redscores.com/pt-br/league/saudi-arabia/pro-league/944",
    #"Austrália - A-League": "https://redscores.com/pt-br/league/australia/a-league/1356",
    #"Brasil - Serie A": "https://redscores.com/pt-br/league/brazil/serie-a/648",
    #"Bélgica - Pro League": "https://redscores.com/pt-br/league/belgium/pro-league/208",
    #"Dinamarca - Superliga": "https://redscores.com/pt-br/league/denmark/superliga/271",
    #"EUA - Major League Soccer": "https://redscores.com/pt-br/league/usa/major-league-soccer/779",
    #"Escócia - Premiership": "https://redscores.com/pt-br/league/scotland/premiership/501",
    #"Espanha - La Liga": "https://redscores.com/pt-br/league/spain/la-liga/564",
    #"França - Ligue 1": "https://redscores.com/pt-br/league/france/ligue-1/301",
    #"Inglaterra - Championship": "https://redscores.com/pt-br/league/england/championship/9",
    #"Inglaterra - League One": "https://redscores.com/pt-br/league/england/league-one/12",
    #"Inglaterra - League Two": "https://redscores.com/pt-br/league/england/league-two/14",
    #"Inglaterra - Premier League": "https://redscores.com/pt-br/league/england/premier-league/8",
    #"Itália - Serie A": "https://redscores.com/pt-br/league/italy/serie-a/384",
    #"Japão - J-League": "https://redscores.com/pt-br/league/japan/j-league/968",
    #"Japão - J2-League": "https://redscores.com/pt-br/league/japan/j2-league/1022",
    #"México - Liga MX": "https://redscores.com/pt-br/league/mexico/liga-mx/743",
    #"Noruega - Eliteserien": "https://redscores.com/pt-br/league/norway/eliteserien/444",
    #"Países Baixos - Eerste Divisie": "https://redscores.com/pt-br/league/netherlands/eerste-divisie/74",
    #"Países Baixos - Eredivisie": "https://redscores.com/pt-br/league/netherlands/eredivisie/72",
    #"Portugal - Primeira Liga": "https://redscores.com/pt-br/league/portugal/primeira-liga/462",
    #"Suécia - Allsvenskan": "https://redscores.com/pt-br/league/sweden/allsvenskan/573",
    #"Suíça - Super League": "https://redscores.com/pt-br/league/switzerland/super-league/591",
    #"Turquia - Super Lig": "https://redscores.com/pt-br/league/turkey/super-lig/600",

    # --- OUTRAS LIGAS ---
    #"África do Sul - Premier League": "https://redscores.com/pt-br/league/south-africa/premier-league/806",
    #"Albânia - Superliga": "https://redscores.com/pt-br/league/albania/superliga/172",
    #"Alemanha - 3. Liga": "https://redscores.com/pt-br/league/germany/3-liga/88",
    #"Argentina - Primera B Nacional": "https://redscores.com/pt-br/league/argentina/primera-b-nacional/645",
    #"Argélia - Ligue 1": "https://redscores.com/pt-br/league/algeria/ligue-1/809",
    #"Armênia - Premier League": "https://redscores.com/pt-br/league/armenia/premier-league/175",
    #"Bolívia - Liga De Futbol Prof": "https://redscores.com/pt-br/league/bolivia/liga-de-futbol-prof/1098",
    #"Brasil - Serie B": "https://redscores.com/pt-br/league/brazil/serie-b/651",
    #"Brasil - Serie C": "https://redscores.com/pt-br/league/brazil/serie-c/657",
    #"Bulgária - Parva Liga": "https://redscores.com/pt-br/league/bulgaria/parva-liga/229",
    #"Bélgica - First Division B": "https://redscores.com/pt-br/league/belgium/first-division-b/211",
    #"Chile - Primera Division": "https://redscores.com/pt-br/league/chile/primera-division/663",
    #"China - Super League": "https://redscores.com/pt-br/league/china-pr/super-league/989",
    #"Colômbia - Liga BetPlay": "https://redscores.com/pt-br/league/colombia/liga-betplay/672",
    #"Coréia do Sul - K League 2": "https://redscores.com/pt-br/league/korea-republic/k-league-2/1362",
    #"Coréia do Sul - K-League 1": "https://redscores.com/pt-br/league/korea-republic/k-league-1/1034",
    #"Croácia - 1. HNL": "https://redscores.com/pt-br/league/croatia/1-hnl/244",
    #"Dinamarca - First Division": "https://redscores.com/pt-br/league/denmark/first-division/274",
    #"Egito - Premier League": "https://redscores.com/pt-br/league/egypt/premier-league/830",
    #"Equador - Liga Pro": "https://redscores.com/pt-br/league/ecuador/liga-pro/696",
    #"Escócia - Championship": "https://redscores.com/pt-br/league/scotland/championship/504",
    #"Escócia - League One": "https://redscores.com/pt-br/league/scotland/league-one/516",
    #"Escócia - League Two": "https://redscores.com/pt-br/league/scotland/league-two/519",
    #"Eslováquia - Fortuna Liga": "https://redscores.com/pt-br/league/slovakia/fortuna-liga/540",
    #"Eslovênia - 1. SNL": "https://redscores.com/pt-br/league/slovenia/1-snl/555",
    #"Espanha - La Liga 2": "https://redscores.com/pt-br/league/spain/la-liga-2/567",
    #"Estônia - Meistriliiga": "https://redscores.com/pt-br/league/estonia/meistriliiga/286",
    #"Finlândia - Veikkausliiga": "https://redscores.com/pt-br/league/finland/veikkausliiga/292",
    #"França - Ligue 2": "https://redscores.com/pt-br/league/france/ligue-2/304",
    #"Grécia - Super League": "https://redscores.com/pt-br/league/greece/super-league/325",
    #"Hungria - OTP Bank Liga": "https://redscores.com/pt-br/league/hungary/otp-bank-liga/334",
    #"Inglaterra - National League": "https://redscores.com/pt-br/league/england/national-league/17",
    #"Irlanda - Premier Division": "https://redscores.com/pt-br/league/republic-of-ireland/premier-division/360",
    #"Irlanda do Norte - Premiership": "https://redscores.com/pt-br/league/northern-ireland/premiership/438",
    #"Islândia - Pepsideild": "https://redscores.com/pt-br/league/iceland/pepsideild/345",
    #"Israel - Ligat ha'Al": "https://redscores.com/pt-br/league/israel/ligat-ha-al/372",
    #"Itália - Serie B": "https://redscores.com/pt-br/league/italy/serie-b/387",
    #"Lituânia - A Lyga": "https://redscores.com/pt-br/league/lithuania/a-lyga/405",
    #"Malásia - Super League": "https://redscores.com/pt-br/league/malaysia/super-league/1052",
    #"Noruega - Obos-Ligaen": "https://redscores.com/pt-br/league/norway/obos-ligaen/447",
    #"Paraguai - Division 1": "https://redscores.com/pt-br/league/paraguay/division-1/755",
    #"País de Gales - Premier League": "https://redscores.com/pt-br/league/wales/premier-league/624",
    #"Peru - Primera Division": "https://redscores.com/pt-br/league/peru/primera-division/764",
    #"Polônia - Ekstraklasa": "https://redscores.com/pt-br/league/poland/ekstraklasa/453",
    #"Portugal - Segunda Liga": "https://redscores.com/pt-br/league/portugal/segunda-liga/465",
    #"Romênia - Liga 1": "https://redscores.com/pt-br/league/romania/liga-1/474",
    #"Suécia - Superettan": "https://redscores.com/pt-br/league/sweden/superettan/579",
    #"Sérvia - Super Liga": "https://redscores.com/pt-br/league/serbia/super-liga/531",
    #"Uruguai - Primera Division": "https://redscores.com/pt-br/league/uruguay/primera-division/770",
    #"Venezuela - Primera Division": "https://redscores.com/pt-br/league/venezuela/primera-division/800",
}

# ==========================================
# Configuração Dinâmica para Flashscore (v2)
# ==========================================
LIGAS_FLASHSCORE = {
    "Brasil - Serie A": {
        "url_base": "https://www.flashscore.com.br/futebol/brasil/brasileirao-betano",
        "pais": "BRAZIL",
        "liga": "Série A",
        "div": "Serie A Betano",
        "league_code": "BRAZIL 1",
        "temporadas": ["2026", "2025", "2024", "2023"]
    },
    "Brasil - Serie B": {
        "url_base": "https://www.flashscore.com.br/futebol/brasil/serie-b",
        "pais": "BRAZIL",
        "liga": "Série B",
        "div": "Serie B",
        "league_code": "BRAZIL 2",
        "temporadas": ["2026", "2025", "2024", "2023"]
    },
    "Brasil - Serie C": {
        "url_base": "https://www.flashscore.com.br/futebol/brasil/serie-c",
        "pais": "BRAZIL",
        "liga": "Série C",
        "div": "Serie C",
        "league_code": "BRAZIL 3",
        "temporadas": ["2026", "2025", "2024", "2023"]
    },
    "Inglaterra - Premier League": {
        "url_base": "https://www.flashscore.com.br/futebol/inglaterra/premier-league",
        "pais": "ENGLAND",
        "liga": "Premier League",
        "div": "Premier League",
        "league_code": "ENGLAND 1",
        "temporadas": ["2025-2026", "2024-2025", "2023-2024", "2022-2023"]
     },
     "Espanha - La Liga": {
         "url_base": "https://www.flashscore.com.br/futebol/espanha/laliga",
         "pais": "SPAIN",
         "liga": "La Liga",
         "div": "La Liga",
         "league_code": "SPAIN 1",
         "temporadas": ["2025-2026", "2024-2025", "2023-2024", "2022-2023"]
     },
     "Itália - Serie A": {
         "url_base": "https://www.flashscore.com.br/futebol/italia/serie-a",
         "pais": "ITALY",
         "liga": "Serie A",
         "div": "Serie A",
         "league_code": "ITALY 1",
         "temporadas": ["2025-2026", "2024-2025", "2023-2024", "2022-2023"]
     }

    # CTRL+K, CTRL+C COMENTAR
    # CTRL+K, CTRL+U REMOVER COMENTARIO
}
